name: nightly

on: push

jobs:
  cut-nightly:
    runs-on: ubuntu-latest
    environment: nightly.yml

    steps:
      - uses: actions/checkout@v3

      - name: ⭐ Cut Nightly ⭐
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_ACCESS_TOKEN }}
        run: |
          HEAD_SHA=$(git rev-parse HEAD)
          NIGHTLY_BRANCH_NAME=$(date --utc "+%y%m%d.6")

          if [[ "${GITHUB_TOKEN}" != ghp_* ]]; then
            echo "This job must have a personal token set as the GITHUB_TOKEN env variable."
            exit 1
          fi

          gh api \
            --method POST \
            --header "Accept: application/vnd.github+json" \
            /repos/${{ github.repository }}/git/refs \
            --field ref="refs/heads/${NIGHTLY_BRANCH_NAME}" \
            --field sha="${HEAD_SHA}"
